apiVersion: v2
name: rtd-ms-ingestor
description: Micro-service designed to process transactions file by emitting each transaction over a kafka queue
type: application
version: 1.0.1
appVersion: 1.0.1
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
