microservice-chart:
  namespace: "rtd"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  podAnnotations: {}

  deployment:
    create: true

  service:
    create: false

  ingress:
    create: false

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534

  envConfig:
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key
    KAFKA_SASL_JAAS_CONFIG_CONSUMER_BLOB_STORAGE_EVENTS: evh-rtd-platform-events-rtd-platform-events-sub-rtd
    KAFKA_SASL_JAAS_CONFIG_PRODUCER_RTD_TRX: evh-rtd-trx-rtd-trx-producer-rtd
    INTERNAL_SERVICES_API_KEY: rtd-internal-api-product-subscription-key
    WALLET_API_KEY: wallet-api-product-subscription-key
    CONTRACT_ID_OBFUSCATION_HMAC_KEY: contract-id-obfuscation-hmac-key
    MONGODB_CONNECTION_URI: mongo-db-connection-uri

  envConfigMapExternals:
    rtdingestor:
      JAVA_TOOL_OPTIONS: JAVA_TOOL_OPTIONS
      CSV_INGESTOR_HOST: CSV_INGESTOR_HOST
      OPENTELEMETRY_LOG_LEVEL: APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL
      WALLET_HOST: WALLET_HOST
      MONGODB_NAME: MONGODB_NAME
      APPLICATIONINSIGHTS_ROLE_NAME: APPLICATIONINSIGHTS_ROLE_NAME
      APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL
      APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED

    rtd-blob-storage-events:
      KAFKA_TOPIC_BLOB_STORAGE_EVENTS: KAFKA_TOPIC_BLOB_STORAGE_EVENTS
      KAFKA_BROKER_PLATFORM_EVENTS: KAFKA_BROKER_RTD

    rtd-trx-producer:
      KAFKA_BROKER_RTD_TRX: KAFKA_BROKER_RTD
