microservice-chart:
  namespace: "rtd"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  podAnnotations: {}

  deployment:
    create: true

  service:
    create: false

  ingress:
    create: false

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534

  terminationGracePeriodSeconds: 900000
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  envConfig:
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    APPLICATIONINSIGHTS_SAMPLING_PERCENTAGE: "100"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "INFO"
    OTEL_TRACES_SAMPLER: "always_on"
    WALLET_CONNECTION_TIMEOUT: "-1"
    WALLET_READ_TIMEOUT: "-1"
    WALLET_REFRESH_PERIOD_MS: "20"
    WALLET_RATE_LIMIT: "1"
    WALLET_RATE_LIMIT_TIMEOUT_MS: "200"
    WALLET_MAX_RETRIES: "5"
    WALLET_RETRY_MAX_INTERVAL_MS: "10"
    THREAD_POOL: "1"
    CONNECTION_POOL: "10"
    CONSUMER_TIMEOUT_MS: "900000" # 15 minutes
    CONSUMER_POLL_SIZE: "1"
    GRACEFUL_SHUTDOWN_TIMEOUT: "15m"

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key
    KAFKA_SASL_JAAS_CONFIG_CONSUMER_BLOB_STORAGE_EVENTS: evh-rtd-platform-events-rtd-platform-events-sub-rtd
    KAFKA_SASL_JAAS_CONFIG_PRODUCER_RTD_TRX: evh-rtd-trx-rtd-trx-producer-rtd
    INTERNAL_SERVICES_API_KEY: rtd-internal-api-product-subscription-key
    WALLET_API_KEY: wallet-api-product-subscription-key
    CONTRACT_ID_OBFUSCATION_HMAC_KEY: contract-id-obfuscation-hmac-key
    MONGODB_CONNECTION_URI: mongo-db-connection-uri

  envConfigMapExternals:
    rtdingestor:
      JAVA_TOOL_OPTIONS: JAVA_TOOL_OPTIONS
      CSV_INGESTOR_HOST: CSV_INGESTOR_HOST
      WALLET_HOST: WALLET_HOST
      MONGODB_NAME: MONGODB_NAME
      APPLICATIONINSIGHTS_ROLE_NAME: APPLICATIONINSIGHTS_ROLE_NAME
      APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL
      APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED

    rtd-blob-storage-events:
      KAFKA_TOPIC_BLOB_STORAGE_EVENTS: KAFKA_TOPIC_BLOB_STORAGE_EVENTS
      KAFKA_BROKER_PLATFORM_EVENTS: KAFKA_BROKER_RTD

    rtd-trx-producer:
      KAFKA_BROKER_RTD_TRX: KAFKA_BROKER_RTD
